{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.15.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.15.0-alpha01-sources.jar",
          "url": "core-ktx-1.15.0-alpha01-sources.jar",
          "size": 70066,
          "sha512": "f0633f783af91e6ec138c5c536aad95fa8e3abcccf75643b6e9939b5ac4f44d3601eab240075a75aa3745009d120e9ba94902680b4bfb4f1eb63e2ec59f76e14",
          "sha256": "2e72bcdc7c2bc3705a37a7c6d2e80954fa7866fc8c93f1c2abd56cadc39ab4f6",
          "sha1": "9e4d33681dd1df39543757c2ccf64b2ac018df23",
          "md5": "0614529ed93e0c6dd1c8cc82a16a075d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.15.0-alpha01.aar",
          "url": "core-ktx-1.15.0-alpha01.aar",
          "size": 170760,
          "sha512": "a63008776f434036c5f81d89843737fc2266403eda4f1ad791c3da44b5673cb2a1507d43ceebf803d142250cbd0623d6bf4ae25096f803434912d2660c342516",
          "sha256": "8720ec7facfa464979d04168cfb2a2db84fdfeb56d8f766d8c7ae1f755bde43f",
          "sha1": "e131f55de7feacbaafb738429580dd424d43975c",
          "md5": "2e1a3cbcfa0a149bfbc9582268bd74fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.15.0-alpha01.aar",
          "url": "core-ktx-1.15.0-alpha01.aar",
          "size": 170760,
          "sha512": "a63008776f434036c5f81d89843737fc2266403eda4f1ad791c3da44b5673cb2a1507d43ceebf803d142250cbd0623d6bf4ae25096f803434912d2660c342516",
          "sha256": "8720ec7facfa464979d04168cfb2a2db84fdfeb56d8f766d8c7ae1f755bde43f",
          "sha1": "e131f55de7feacbaafb738429580dd424d43975c",
          "md5": "2e1a3cbcfa0a149bfbc9582268bd74fc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-ktx-1.15.0-alpha01-versionMetadata.json",
          "url": "core-ktx-1.15.0-alpha01-versionMetadata.json",
          "size": 42717,
          "sha512": "d94e7af20884072ba66f3e89dbd1b4e1823156d64bae821674229d47b5a48aa8d552ab42628b5a4d51286814390f8bf4a848006c3653a783e1d324ac6e643eea",
          "sha256": "261dcd3c8616cae91271d5163997c45b8b509af204786420649a0b7e0f245281",
          "sha1": "9ccd1b46b95778109472c0a16ddd08e4bef021f0",
          "md5": "e320a403a93dad70e1c5d328f07a9e93"
        }
      ]
    }
  ]
}