{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.15.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.15.0-alpha01-sources.jar",
          "url": "core-1.15.0-alpha01-sources.jar",
          "size": 935414,
          "sha512": "a52e781e4ff8e25039f1762a84cc4f57fd8411ab1b13035b19f0a7b779b05db91be0d66710642b6c394e9c820e9753811db67d4fe6bc9cea122b3f2d630e8be8",
          "sha256": "492379e08a4fcb8b3ee66be961fa0db92cc26e0c1afeb430e735e84facb0b325",
          "sha1": "c9e4f7f66f8a4a74f434745ac70e2bf5313ceaf8",
          "md5": "2f188f572af2ded9e42b467ac8b83fa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.15.0-alpha01.aar",
          "url": "core-1.15.0-alpha01.aar",
          "size": 1246634,
          "sha512": "4cb93582ebef1014b444408d73e95d12450f048a984faa99beaa72ed9374922e4a3da7955c9794d6f7bb3bf1c2401f2fabfb9e9cda61ba370d564489aeb7b145",
          "sha256": "5f5c57185324b2f08310642052f5f1e94b4b11478174c3b38267f804b47ec664",
          "sha1": "5cf16cc9f19038df57c1be8e7a596408362da741",
          "md5": "59a2c8d89f196347a00ee9e65bdcc939"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.15.0-alpha01.aar",
          "url": "core-1.15.0-alpha01.aar",
          "size": 1246634,
          "sha512": "4cb93582ebef1014b444408d73e95d12450f048a984faa99beaa72ed9374922e4a3da7955c9794d6f7bb3bf1c2401f2fabfb9e9cda61ba370d564489aeb7b145",
          "sha256": "5f5c57185324b2f08310642052f5f1e94b4b11478174c3b38267f804b47ec664",
          "sha1": "5cf16cc9f19038df57c1be8e7a596408362da741",
          "md5": "59a2c8d89f196347a00ee9e65bdcc939"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.15.0-alpha01-versionMetadata.json",
          "url": "core-1.15.0-alpha01-versionMetadata.json",
          "size": 262558,
          "sha512": "abab25917ded5badbe2ed543e617ba6810438831f45742c6bac4cbe87805055d8c57bf9f270a4a2b86b0f90f6e8dfb210a122f424acba126e1090f68ae2a4217",
          "sha256": "e8511946a6c25f1a5353595edfc315e5515995248ec281a30f899f81e0637a28",
          "sha1": "96e1ca3c1dc288f671d647a2b8e4c25b8dd02c74",
          "md5": "3af339324f8ec7c7951c3d5ecae48c49"
        }
      ]
    }
  ]
}